---
title: "Data Visualization Assignment GGPlot2"
author: "Alaysia Ezzard"
date: "2025-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GGPlot2 Assignment

For this assignment I recreated the visualizations I made in last weeks data viz assignment.

**Loading Libraries**

```{r}
library(tidyverse)
library(scales)
library(treemapify)
library(RColorBrewer)
library(svglite)
library(ggplot2)
```

**Uploading Data**

```{r}
airline_safety <- read.csv("airline-safety.csv") 
```

**Data Visualization 1:** Bar Chart

```{r}
airline_safety_bar_chart <- airline_safety |> group_by(airline) |> 
  filter(airline== "Aeroflot*")
```

```{r}
year <- c(rep("1985-1999", 1), rep("2000-2014", 1))
condition <- rep(c("fatal_accidents_85_99","fatal_accidents_00_14","incidents_85_99","incidents_00_`14"),1)
value<- abs(c(14,1,76,6))
data<- data.frame(year,condition,value)
```

```{r}
ggplot(data, aes(fill=condition, y=value, x=year)) + geom_bar(position="stack", stat="identity")+ 
  labs(title = "Aeroflot improved in safety", subtitle = "Between 1985 and 1999, Aeroflot had the highest number of incidents out of all airlines for those years at 76, with 14 of those being fatal. Between 2000 and 2014, the airline had six incidents, with one being fatal.", caption = "Source: FiveThirtyEight \n by Alaysia Ezzard")
```

**Data Visualization 2:** Doughnut Chart

```{r}
data<- data.frame(category=c("Malaysia Airlines", "American", "Air France", "Kenya Airways","China Airlines"), count=c(537,416,337,283,225))

data$fraction = data$count/sum(data$count)

data$ymax = cumsum(data$fraction)

data$ymin = c(0, head(data$ymax, n=-1))

ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
  geom_rect() + 
  coord_polar(theta="y") +
  xlim(c(2, 4)) +
  theme_void() + 
  labs(title = "Top five airlines with the most fatalities from 2000 to 2014", subtitle = "From 2000 to 2014, Malaysia Airlines had the most fatalites, though they only had three incidents with two being fatal in those 14 years.", caption = "Source: FiveThirtyEight \n by Alaysia Ezzard")
```

**Data Visualization 3:** Polar Area Chart

```{r}
data <- data.frame(
  Category = c("Alaska Airlines", "Hawaiian Airlines", "Southwest Airlines", "United", "American", "Delta"), 
  Value = c(5, 1, 8, 14, 17, 24)
)

plot <- ggplot(data, aes(x = Category, y = Value, fill = factor(Category))) +
      geom_col(width = 1, color = "white")

plot <- plot + coord_polar() +
  theme_void() + labs(title = "Hawaiian Airlines was the safest U.S. based airline between 2000 and 2014", subtitle = "Out of the airlines based in the U.S., Hawaiian Airlines only had one incident, which was not fatal, in that 14 year period. Southwest is the only other airline that did not have a fatal incident.", caption = "Source: FiveThirtyEight \n by Alaysia Ezzard")
  

plot
```
